name: smart_phishing_detection_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Keep this if you need localization
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  firebase_database: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png